namespace Spectacles.NET.Types
{
	public enum MessageType
	{
		DEFAULT,
		RECIPIENT_ADD,
		RECIPIENT_REMOVE,
		CALL,
		CHANNEL_NAME_CHANGE,
		CHANNEL_ICON_CHANGE,
		CHANNEL_PINNED_MESSAGE,
		GUILD_MEMBER_JOIN,
		USER_PREMIUM_GUILD_SUBSCRIPTION,
		USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_1,
		USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_2,
		USER_PREMIUM_GUILD_SUBSCRIPTION_TIER_3
	}
}
