name: Docs
on:
  push:
    branches:
    - master
    - docs
  release:
    types: [created]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout Git
      - uses: nikeee/docfx-action@master
        name: Build Documentation
        with:
          args: .docs/docfx.json
      - name: Move docs
        run: |
          branch=$(echo ${{ github.ref }} | cut -d '/' -f 3- -)
          mkdir docs
          mkdir -p $branch
          mv .docs/_site docs/$branch
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
        with:
          keepFiles: true