name: Docs
on:
  push:
    branches:
    - master
    - stable
  release:
    types: [created]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout Git
      - uses: nikeee/docfx-action@master
        name: Build Documentation
        with:
          args: .docs/docfx.json
      - name: Move docs
        run: |
          mkdir -p docs/${GITHUB_REF#refs/heads/}
          sudo mv .docs/_site/* docs/${GITHUB_REF#refs/heads/}
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_PAT }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
        with:
          keepFiles: true