name: Docs
on:
  push:
    branches:
    - master
  release:
    types: [created]
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nikeee/docfx-action@master
        name: Build Documentation
        with:
          args: .docs/docfx.json
  
    # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: .docs/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages